# basic
bs_train : 1
bs_test : 1
workers : 2
max_epoch : 400
step_per_update: 4

# model
pretrained_i3d_weight : 'models/model_rgb.pth'
event : 'sync10m'
labelType : 'DN'
view : 'V1'
suffix : '64x4_S2Separate_MixSA_l3_AB'
# dataset-数据集
data_root : '/home/xx/BBB-Sync/Dataset_Segment64_4/'
train_root : '/home/xx/BBB-Sync/Dataset_Segment64_4/'

# Annotation-标签
#coarse_path : 'Annotations/FineDiving_coarse_annotation.pkl'
coarse_path : '/home/xx/BBB-Sync/Dataset_Segment64_4/'
label_path : '/home/xx/BBB-Sync/Dataset_Segment64_4/'
train_anno_path : '/home/xx/BBB-Sync/Dataset_Segment64_4/'

# Split-训练集测试集划分
#label_path : 'Annotations/fine-grained_annotation_aqa.pkl'
#train_split : 'Annotations/train_split.pkl'
train_split : '/home/xx/BBB-Sync/Dataset_Segment64_4/'
test_split : '/home/xx/BBB-Sync/Dataset_Segment64_4/'

# optimizer
optimizer: 'Adam'
weight_decay : 0.00001
base_lr : 0.00001
lr_factor : 1

# others
seed : 0
frame_length : 96
voter_number : 10
#print_freq : 40
print_freq : 40
usingDD: True
fix_size : 5
step_num : 3
prob_tas_threshold : 0.25
random_choosing : False
action_number_choosing: True




